apiVersion: v1
kind: ConfigMap
metadata:
  name: openedx-config
  namespace: openedx
  labels:
    app.kubernetes.io/part-of: futurelib
data:
  # These are non-secret runtime settings. Secrets live in openedx-secrets.
  PLATFORM_NAME: "FutureLib"
  LMS_HOST: "lms.futurelib.gov.lr"
  CMS_HOST: "studio.futurelib.gov.lr"
  PREVIEW_LMS_HOST: "preview.lms.futurelib.gov.lr"
  LANGUAGE_CODE: "en"
  TIME_ZONE: "Africa/Monrovia"
  CONTACT_EMAIL: "support@futurelib.gov.lr"
  DEFAULT_FROM_EMAIL: "noreply@futurelib.gov.lr"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "openedx"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  ELASTICSEARCH_HOST: "elasticsearch"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
