apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openedx

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - lms-deployment.yaml
  - cms-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml

# For production overlays, use:
# patches:
#   - path: overlays/production/replicas.yaml
